print(int(29))
print("I am "+ (str(29)) + " years of age")
var=str(29)
print(var)
var=str(0)
print(var)
var=int(29)
print(var)
var=int(3.14)
print(var)
var=float('3.14')
print(var)
var=float(3)
print(var)
var=int(5.55)
print(var)